## Introduction to Python

#### Average versus median

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("mlb.csv")
df = df[['Height', 'Weight']]
df
baseball = df.values.tolist()

In [2]:
# np_baseball is available
np_baseball = np.array(baseball)
np_baseball

array([[ 74, 180],
       [ 74, 215],
       [ 72, 210],
       ...,
       [ 75, 205],
       [ 75, 190],
       [ 73, 195]])

Create np_height_in from np_baseball

In [4]:
np_height_in = np_baseball[:,0]
np_height_in

array([74, 74, 72, ..., 75, 75, 73])

print out the mean of np_height_in

In [6]:
np.mean(np_height_in)

73.6896551724138

print out the median of np_height_in

In [5]:
np.median(np_height_in)

74.0

In [14]:
np.corrcoef(np_city[:, 0], np_city[:, 1])

array([[1.00000000e+00, 6.79445649e-04],
       [6.79445649e-04, 1.00000000e+00]])

In [15]:
# [row, column]
np.std(np_city[:, 0])

0.2006718336389041