# Introduction to Python

## NumPy

#### Type of NumPy Arrays

In [2]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])

In [3]:
type(np_height)

numpy.ndarray

In [4]:
type(np_weight)

numpy.ndarray

#### 2D NumPy Arrays

In [6]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79], [65.4, 59.2, 63.6, 88.4, 68.7]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [7]:
np_2d.shape

(2, 5)

In [8]:
np.array([[1.73, 1.68, 1.71, 1.89, 1.79], [65.4, 59.2, 63.6, 88.4, 68.7]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

#### Subsetting

In [9]:
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [10]:
np_2d[0][2]

1.71

In [11]:
np_2d[0, 2]

1.71

In [12]:
np_2d[:, 1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [13]:
np_2d[1, :]

array([65.4, 59.2, 63.6, 88.4, 68.7])