# Introduction to Python

## NumPy

#### List Recap
* Powerful
* Collection of values
* Hold different types
* Change add, remove
* need for Data Science
* Need for Data Science
  * mathematical operations over collections
  * speed

#### Illustration

In [1]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
height

[1.73, 1.68, 1.71, 1.89, 1.79]

In [2]:
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
weight

[65.4, 59.2, 63.6, 88.4, 68.7]

In [3]:
weight / height ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

#### Solution: NumPy
* Numeric Python
* Alternative to Python List: NumPy Array
* Calculations over entire arrays
* Easy and fast
* Installation
  * In the terminal: `pip3 install numpy`

####  NumPy

In [5]:
import numpy as np
np_height = np.array(height)
np_height

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [7]:
np_weight = np.array(weight)
np_weight

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [8]:
bmi = np_weight / np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

#### Comparisons

In [9]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
weight / height ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [10]:
np_height = np.array(height)
np_weight = np.array(weight)
np_weight / np_height ** 2

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

#### NumPy: remarks

In [11]:
np.array([1.0, "is", True])

array(['1.0', 'is', 'True'], dtype='<U32')

* NumPy arrays: contain only one type

#### NumPy: remarks

In [12]:
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

In [13]:
python_list + python_list

[1, 2, 3, 1, 2, 3]

In [14]:
numpy_array + numpy_array

array([2, 4, 6])

* Different types: different behavior!

#### NumPy Subsetting

In [15]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [16]:
bmi[1]

20.97505668934241

In [17]:
bmi > 23

array([False, False, False,  True, False])

In [18]:
bmi[bmi > 23]

array([24.7473475])