### Packages

#### Motivation
* Functions and methods are powerful
* All code in Python distribution?
    * Huge code base: messy
    * Lots of code you won't use
    * Maintenance problem

#### Packages
* Directory of Python Scrips
* Each script = module
* Specify functions, methods, types
* Thousands of packages available
    * NumPy
    * Matplotlib
    * scikit-learn

#### Install package
* Download `get-pip.py`
* Terminal:
    * `python3 get-pip.py`
    * `pip3 install numpy`

#### Import package

In [1]:
import numpy
array([1, 2, 3])

NameError: name 'array' is not defined

In [2]:
numpy.array([1, 2, 3])

array([1, 2, 3])

In [3]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

In [4]:
from numpy import array
array([1, 2, 3])

array([1, 2, 3])